 export const columnInfo = [
   {id: 'name', name: 'Name', hidden: false},
   {id: 'type', name: 'Type', hidden: false},
   {id: 'date', name: 'Date', hidden: false},
   {id: 'study_name', name: 'Study Name', hidden: false},
   {id: 'institute', name: 'Institute', hidden: false},
   {id: 'researcher', name: 'Researcher', hidden: false},
   {id: 'reference', name: 'Reference', hidden: false},
   {id: 'contact', name: 'Contact', hidden: false},
   {id: 'assembly_id', name: 'Accession ID', hidden: false},
   {id: 'assembly_reference', name: 'Accession Ref', hidden: false},
   {id: 'chromosome', name: 'Chromosome', hidden: false},
   {id: 'assembly_start', name: 'Chr Start', hidden: false},
   {id: 'assembly_end', name: 'Chr End', hidden: false},
   {id: 'report', name: 'Report', hidden: false},
 ];
