 export const columnInfo = [
   {id: 'name', name: 'Name', hidden: false},
   {id: 'chain', name: 'Chain', hidden: true},
   {id: 'row_reads', name: 'Reads', hidden: false},
   {id: 'date', name: 'Date', hidden: true},
   {id: 'samples_group', name: 'Sample Group', hidden: true},
   {id: 'patient_name', name: 'Patient', hidden: true},
   {id: 'sex', name: 'Sex', hidden: true},
   {id: 'ethnic', name: 'Ethnicity', hidden: true},
   {id: 'status', name: 'Condition', hidden: true},
   {id: 'cohort', name: 'Cohort', hidden: true},
   {id: 'age', name: 'Age', hidden: true},
   {id: 'name_in_paper', name: 'Name in Study', hidden: true},
   {id: 'country', name: 'Country', hidden: true},
   {id: 'study_name', name: 'Study', hidden: true},
   {id: 'institute', name: 'Institute', hidden: true},
   {id: 'researcher', name: 'Researcher', hidden: true},
   {id: 'num_subjects', name: '# Subjects', hidden: true},
   {id: 'num_samples', name: '# Samples', hidden: true},
   {id: 'study_reference', name: 'Study Ref', hidden: true},
   {id: 'study_contact', name: 'Study Contact', hidden: true},
   {id: 'study_acc_id', name: 'Study Acc ID', hidden: true},
   {id: 'study_acc_ref', name: 'Study Acc Ref', hidden: true},
   {id: 'tissue_name', name: 'Tissue Name', hidden: true},
   {id: 'species', name: 'Species', hidden: true},
   {id: 'tissue', name: 'Tissue', hidden: false},
   {id: 'combined_cell_type', name: 'Cell', hidden: false},
   {id: 'cell_type', name: 'Cell Type', hidden: true},
   {id: 'sub_cell_type', name: 'Cell Subtype', hidden: true},
   {id: 'isotype', name: 'Isotype', hidden: true},
   {id: 'sequencing_protocol', name: 'Protocol', hidden: true},
   {id: 'umi', name: 'UMI', hidden: false},
   {id: 'sequencing_length', name: 'Read Length', hidden: false},
   {id: 'primer_3_loc', name: '3\' Primer', hidden: true},
   {id: 'primer_5_loc', name: '5\' Primer', hidden: true},
   {id: 'seq_platform', name: 'Platform', hidden: true},
   {id: 'helix', name: 'Helix', hidden: true},
   {id: 'genotypes', name: 'Genotype', hidden: false},
   {id: 'haplotypes', name: 'Haplotypes', hidden: false},
   {id: 'dataset', name: 'Dataset', hidden: false},
 ];
