 export const columnInfo = [
   {id: 'name', name: 'Name', hidden: false},
   {id: 'imgt_name', name: 'IMGT Name', hidden: false},
   {id: 'type', name: 'Type', hidden: false},
   {id: 'novel', name: 'Novel', hidden: false},
   {id: 'sequence', name: 'Sequence', hidden: false},
   {id: 'gapped_sequence', name: 'Gapped', hidden: false},
   {id: 'feature', name: 'Feature', hidden: false},
   {id: 'start', name: 'Start', hidden: false},
   {id: 'end', name: 'End', hidden: false},
   {id: 'score', name: 'Score', hidden: false},
   {id: 'strand', name: 'Strand', hidden: false},
   {id: 'frame', name: 'Frame', hidden: false},
   {id: 'refseq_name', name: 'Reference', hidden: false},
   {id: 'refseq_sequence', name: 'Ref Sequence', hidden: false},
   {id: 'sample_name', name: 'Sample', hidden: false},
];
